name: update demo

on:
  workflow_dispatch:

jobs:
  update-demo:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-go@19bb51245e9c80abacb2e91cc42b33fa478b8639 # v4.2.1
        with:
          go-version-file: go.mod
      - name: install sheep
        run: |
          go install .
          sheep --version

      - uses: charmbracelet/vhs-action@59641cdc7fadf3978db65eb8c6937ea2752f4ec3 # v2.1.0
        with:
          path: ./tapes/demo.tape
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5 # v5.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: update demo
          body: ${{ github.sha }}
          branch: docs/update-demo
          branch-suffix: short-commit-hash
